### ISSUE TITLE
Add "template" verb

### ISSUE THREAD

**Issue by mrdvt92** [johnkerl/miller#580]
Unfortunately I could not get either `cut` or `unsparsify` to do what I need.  I need csv out with the EXACT column headers of a template file.  Then mlr would reorder, cut and unsparsify to make the data fit that template file header.  Maybe it is possible but I could not get it to work.

This comes very close except when the input data does not contain all columns needed.  My template has 90 columns.

mlr --csv unsparsify input*.csv | mlr -csv cut -o -f "`head -n 1 template.csv | sed -e 's/"//g'`" > output.csv #581

What I recommend is something like this
```
mlr --csv template -t template.csv input*.csv > output.csv
mlr --ijson --ocsv template -t template.csv input*.json > output.csv
mlr --csv template -f 'a,b,c' input*.csv > output.csv
```
```
cat template.csv
"a","b","c"
1,2,3
```
```
cat input.csv
c,a,d,e,f
1,2,3,4,5
```
```
cat output.csv
a,b,c
1,,3
```

**Comment by johnkerl** [comment]
This is an awesome suggestion @mrdvt92 !! :D

**Comment by johnkerl** [comment]
@mrdvt92 https://github.com/johnkerl/miller/pull/594 is WIP. It still needs the read-from-file option (`-t`), and it needs regression tests.

I like this feature _so much_. :D

**Comment by johnkerl** [comment]
@mrdvt92 https://github.com/johnkerl/miller/pull/594 is merged for Miller 6

**Comment by mrdvt92** [comment]
> @mrdvt92 #594 is merged for Miller 6

How do I test this merge?

I pulled the main branch and compiled it but I got the error verb not found.

```
$ ~/temp/mlr-5.10.2/c/mlr --icsv --ocsv template -t template.csv in.csv > out.csv
mlr: verb "template" not found. Please use "mlr --help" for a list.
```

```
$ git clone https://github.com/johnkerl/miller.git mlr/
$ cd mlr/
$ autoreconf -f -i
$ ./configure
$ make
```
```
$ ./c/mlr template
mlr: verb "template" not found. Please use "mlr --help" for a list.
```
```
$ ./c/mlr --version
Miller 5.10.2-dev
```
```
$ date -u
Fri Jul  9 17:46:48 UTC 2021
```

**Comment by johnkerl** [comment]
Sorry @mrdvt92 this is in the Go port which will be Miller 6.

https://github.com/johnkerl/miller/blob/main/go/README.md

**Comment by mrdvt92** [comment]
CentOS 7 does not have go 1.16 yet. just 1.15... :-(

```
src/lib/readfiles.go:53:18: undefined: os.ReadDir
note: module requires Go 1.16
```

**Comment by johnkerl** [comment]
@mrdvt92 gurg

that's not good, & i didn't know that about CentOS

i'll undo the `os.ReadDir` mod & delay any 1.16 requirements for somewhen in the future

thanks for letting me know!! :)

**Comment by aborruso** [comment]
@johnkerl is it possible to test it using these binaries https://github.com/johnkerl/miller/actions/runs/1012962769 ?

Could it a solution also for @mrdvt92 ?

**Comment by johnkerl** [comment]
@aborruso good call, that should work! :)

Meanwhile this has alerted me that Go 1.16 isn't available everywhere so (looking toward release) I should make sure Miller builds with Go 1.15.

**Comment by johnkerl** [comment]
@mrdvt92 https://github.com/johnkerl/miller/commit/a8202d17e2bba61d0e3ba3a21c8cc64c2ce963e7 goes back to 1.15. Also, binaries as noted above by @aborruso should work -- please let me know of any issues.

**Comment by mrdvt92** [comment]
## Testing Notes

### Would we ever what a JSON template?  

Do we need to add `--csv` or `--json` options?

### fill with option and types

I have been playing with the new `template` verb but the `--fill-with` option does not appear to support the new go port concept of preserving types. The current `--fill-with` only supports string types.

```
$ echo -ne "a\r\n1\r\n" | ./mlr --icsv --ojson template --fill-with 'null' -f "a,b,c"
{
  "a": 1,
  "b": "null",
  "c": "null"
}
```
We might want to re-think the fill to support JSON types in the input similar to how Node-Red does types with the JSONata inputs.

```
--fill-with-typed '""'   -- current default empty string
--fill-with-typed null   -- recommended default
--fill-with-typed 0      -- number
--fill-with-typed '"a"'  -- string -- the shell requires the quotes wrapping
--fill-with-typed false
```

## Unrelated Issues Noted While Testing

### tee verb with append mode should suppress header when file exists

While I was playing around I also noticed an issue with "tee" -a option does not support suppressing of header when appending to existing file.  I expect when file does not exists the CSV header would be printed.  However, when file exists the header would be suppressed.  I have no idea how `-a` should support JSON files except maybe JSONP.

```
$ rm out.csv
$ cat abc.csv | ./mlr --icsv tee --ocsv -a out.csv then nothing
$ cat out.csv
a,b,c
1,2,3
$ cat abc.csv | ./mlr --icsv tee --ocsv -a out.csv then nothing
$ cat out.csv
a,b,c
1,2,3
a,b,c
1,2,3
```
 At this point I expect the file to be 

```
a,b,c
1,2,3
1,2,3
```

### mlr should be able to run without shell

There appears to be no way to use `cat` verb with `then` pipelining so there is no way to run the mlr app without the shell since there is no way to set up a pipeline without shell meta characters like `|` and `>` or `<`.  

The requires the shell due to the use of `|` and `>`
```
$ cat abc.csv | ./mlr --icsv --ocsv cut -f a > out.csv
```
To remove the need for output redirection `>`
```
$ cat abc.csv | ./mlr --icsv --ocsv cut -f a then tee --ocsv out.csv then nothing
```
This should be something like the below where we no longer require the shell to run the command.
```
$ ./mlr --icsv --ocsv cat abc.csv then cut -f a then tee --ocsv -a out.csv then nothing 
mlr :  open then: no such file or directory
```
I recommend adding support to the `cut` verb for the "--" argument like `grep` or adding a stop at the empty file "" or adding a new `input` verb.
```
$ ./mlr --icsv --ojson cat "abc.csv" "" then cut -f "a"
$ ./mlr --icsv --ojson cat "abc.csv" -- then cut -f "a"
$ ./mlr --icsv --ojson input --csv -f "abc.csv" then cut -f "a"
$ ./mlr --icsv --ojson input --csv -d "a,b,c\r\n1,2,3\r\n" then cut -f "a"
$ ./mlr --ijson --ocsv input --json -d '{ "a":1,"b":2,"c":3}' then cut -f "a"
```

**Comment by johnkerl** [comment]
Thanks @mrdvt92 ! I'll open separate issues to track the above requests. :)

**Comment by johnkerl** [comment]
@mrdvt92 do you know about `--from`?

**Comment by johnkerl** [comment]
For tracking I prefer to leave these open until the Go port is released. (Since that is non-trivial and non-immediate
